### ISSUE TITLE
Great Plugin!

### ISSUE THREAD

**Issue by Exeedy** [Electry/VitaGrafix#1]
Thank you thats really a great plugin!
More supported games would be awesome =)

Greetz

**Comment by SuperROBO-1** [comment]
Agreed, playing P4G at 544p is fascinating on both the vita and pstv

Cant wait for more great things to be done with this

**Comment by greggameplayer** [comment]
@SuperROBO-1 do you know that a plugin like that exist way before which is called vitarescale and has been created by Rinnegatamante

**Comment by JuanD817** [comment]
God of war collection looks awesome now with the patch

**Comment by EulenCarbon** [comment]
Amazing man，now God of War collections deserve the name of HD collections.
