### ISSUE TITLE
What is the difference between FB and IB?

### ISSUE THREAD

**Issue by RyuSeisuke1992** [Electry/VitaGrafix#10]

**Comment by Electry** [comment]
FB or framebuffer is the final "image" that is being drawn on the screen. As per [VitaSDK](https://github.com/vitasdk/vita-headers/blob/master/include/psp2/display.h#L45), this can only use 480x272, 640x368, 720x408 or 960x544 resolutions.

IB or internal buffer is a "canvas" that some games use to render their 3D world separately from other things like UI/HUD. This allows them to render UI at native res, and then upscale 3D graphics from a lower resolution.

Changing framebuffer resolution does affect everything that is drawn on the screen, while changing internal buffer res. only impacts what's that buffer used for (in this case actual game world graphics).

Check the final section of README.md to see what is patched in which games.

**Comment by RyuSeisuke1992** [comment]
thank you
