### ISSUE TITLE
[REQUEST]Fate/EXTELLA LINK is a new work. is OK？

### ISSUE THREAD

**Issue by yeqing1990** [Electry/VitaGrafix#100]
SEGA Games announces that it is expected to launch the PlayStation Vita platform action game Fate / EXTELLA LINK for Hong Kong, China, Taiwan, South Korea and Southeast Asia on September 13, 2018.

This game is worth playing if there is HD. If necessary, I can provide EBOOT.

**Comment by yeqing1990** [comment]
pcsh10121

**Comment by yeqing1990** [comment]
@Electry
Strangely enough, I turned eboot. bin into eboot. elf and used IPA to open the card, but the game could be installed and run on VITa. PS: originally, I wanted to find out the address of the resolution, so the first step got stuck.

**Comment by dark-kyon** [comment]
I don't think resolution is the issue here, i checked the game, was slightly downgraded to get better framerate than the first game, now the textures are worse and the characters look uglier because they used the new designs that push the PS4 hardware, but Vita can't render to a acceptable framerate.

**Comment by Electry** [comment]
It's running at 720x408 4x MSAA

720x408 is nowhere to be found in the eboot.bin.elf, but after some digging I found out that the res is actually calculated from 960x544 (so no plain reference to 720x408).

After patching, 960x544 seems to be working just fine. I'll include patch for this in the next release.

**Comment by yeqing1990** [comment]
I also tried to modify his EBOOT and found that the game was 960x544, but his tree and other objects had very low resolution.
