### ISSUE TITLE
[REQUEST] Borderlands 2 - PCSF00576

### ISSUE THREAD

**Issue by vicadinsx** [Electry/VitaGrafix#101]
Hi guys!

Could you please just add the version PCSF00576 of borderlands 2?
I bet you just have to add that to games.c :)

**Comment by vicadinsx** [comment]
So I decided to install vitasdk and try it by myself and is working as expected, just changed this line:

else if (!strncmp(titleid, "PCSF00570", 9) || // Borderlands 2 [EUR] [1.07]
			**!strncmp(titleid, "PCSF00576", 9) || // Borderlands 2 [EUR-2] [1.07]**
			!strncmp(titleid, "PCSE00383", 9)) { // Borderlands 2 [USA] [1.09]

Guess there are 2 european versions.

**Comment by fidzerone** [comment]
Could you add japan version too?
PCSG0040 Borderlands 2 ボーダーランズ2

**Comment by vicadinsx** [comment]
@fidzerone 
I think it's the version PCSG00400 (one more zero), I added it and also compiled the file if you want to try:

[VitaGrafix Borderlands.zip](https://github.com/Electry/VitaGrafix/files/2414838/VitaGrafix.Borderlands.zip)

**Comment by Electry** [comment]
Hey, thanks for letting us know. I'll add it. (japan version too, as soon as someone confirms that it's working)

**Comment by vicadinsx** [comment]
Thanks Electry :)

**Comment by Electry** [comment]
PCSG00400 added in https://github.com/Electry/VitaGrafixPatchlist/commit/6cc6bc790f46cff42e45ad255571a3a287463557

closing the issue
