### ISSUE TITLE
[REQUEST] Jack And Daxter FPS 

### ISSUE THREAD

**Issue by naxeras** [Electry/VitaGrafix#103]
Hi,

Game its capped at 20 fps no matter overclock or downclock and its ugly.

It is possible remove fps cap?

Regards

**Comment by SheidCraft** [comment]
When the fps limit is removed, the game speed also increases. Maybe if there is an opportunity to install a lock for 25/24 the speed will not be so noticeable

**Comment by Electry** [comment]
IIRC the code that handles frame-limiting is the same in Jak 1 (20 fps) and Jak 2/3 (30 fps), so there must be a way to remove that 20 fps cap (perhaps somewhere else).

**Comment by Electry** [comment]
added earlier in https://github.com/Electry/VitaGrafixPatchlist/commit/8340c911ca09bf71badea88f7be67b20d8d5cff4 :)
