### ISSUE TITLE
[REQUEST] Uncharted Golden Abyss

### ISSUE THREAD

**Issue by VitaNewbie** [Electry/VitaGrafix#104]
Is it possible to add support for resolution boost.

**Comment by SheidCraft** [comment]
Already was. But yes, I hope and expect a release, or an answer why it is impossible.

**Comment by Wontell** [comment]
+1 I also would like to request this, but it looks like this project is dead, he was updating,adding games almost weekly now he quit, so i think the Coder doode just got bored by this

**Comment by yaefeni1986** [comment]
A resolution patch for this game would be nice game is blurry

**Comment by Electry** [comment]
added in https://github.com/Electry/VitaGrafixPatchlist/commit/14fe4e0064bc9e538496f44c2e24ecb6131be450
