### ISSUE TITLE
[REQUEST] Dragon Ball Battle of Z Native Res

### ISSUE THREAD

**Issue by Canzah** [Electry/VitaGrafix#109]
I tried Battle of Z and despite some claims on Vita roundup blog that it's native res, it looks very clearly sub-native res to me with only UI being rendered at native resolution.
Is there any chance for support for this game to allow native resolution for the actual 3D elements and not just UI?
Basically, another Persona 4 Golden situation.

**Comment by Electry** [comment]
Yep, in-game world is rendered at 704x448 (4x MSAA). I'll include a patch for this in my next test-build.

**Comment by Shinriji** [comment]
I tested DBZ Battle of Z (US) for about 1 hour and there is no issues with the game. Framerate was a stable 30FPS with 960x544 (500mhz OC), but the IQ improved very little IMO.

**Comment by Canzah** [comment]
Seems it got added, thanks, closing the issue.
