### ISSUE TITLE
Killzone Mercenary (PCAS00107) - Crashes with plugin

### ISSUE THREAD

**Issue by ImplyingKinpatsu** [Electry/VitaGrafix#11]
I haven't found anyone else who has the US version to confirm this, however using the plugin crashes the game after the manual warning sign stays on screen for a few seconds

**Comment by Electry** [comment]
Hey,
are you on the latest version? It's 1.12 iirc
Also, do you use cartrige, nonpdrm or other dump?

**Comment by ImplyingKinpatsu** [comment]
I am on 1.12 using a NoNpDRM version

**Comment by Electry** [comment]
Interesting,
did you make any changes to the config file?

**Comment by ImplyingKinpatsu** [comment]
I tried it with no changes to the config file and then with OSD disabled

**Comment by Electry** [comment]
Could you try updating kuio to v1.2? (if you haven't already)

Other than that, I have no idea, I did a quick check and it didn't crash for me on PCSA00107 NoNpDrm.

**Comment by ImplyingKinpatsu** [comment]
I don't know if kuio changed, but it works now

**Comment by Electry** [comment]
great!
