### ISSUE TITLE
[REQUEST] I have found resolution address of some games. 

### ISSUE THREAD

**Issue by FormerNoob** [Electry/VitaGrafix#117]
Hello,Electry.According to your tutorial,I found some address of these games(All of them are movs.w).

I don't know whether they are right or not,but they work.They run at 960x544p.I want to play them at the version both of mai and nnd,but sorry I can't find the address of nnd version. If possible,could you please add the support and write in the plug-in for them? If you need other things，i would  provide.

 Maybe I  have done something wrong about the address. Please tell me.
Thank you very much.@Electry

Trails of Coldsteel1&2:   720x408 and 736x408 must be changed together, or it would be crash. 

ADDRESS:
Legend of Heroes: Trails of Coldsteel1 ([PCSH00074][ASIA][v1.03][DLC][Mai233]) :
720x408	2D0x198

	0x000FAA0C: 0x7134F45F '_.4q' - movs.w     a2, #0x2d0
	0x000FAA10: 0x72CCF45F '_..r' - movs.w     a3, #0x198

736x408	2E0x198

	0x000FAA42: 0x7238F45F '_.8r' - movs.w     a3, #0x2e0		
	0x000FAA46: 0x73CCF45F '_..s' - movs.w     a4, #0x198

Legend of Heroes: Trails of Coldsteel2 ([PCSH00075][ASIA][v1.03][DLC][Mai233]) :
720x408	2D0x198	

	0x0013AAE8: 0x7134F45F '_.4q' - movs.w     a2, #0x2d0
	0x0013AAEC: 0x72CCF45F '_..r' - movs.w     a3, #0x198

736x408	2E0x198

	0x0013AB28: 0x7138F45F '_.8q' - movs.w     a2, #0x2e0
	0x0013AB2C: 0x72CCF45F '_..r' - movs.w     a3, #0x198

Dead or Alive Xtreme Volleyball([PCSH00250][ASIA][v1.12][DLC][Mai233]):
640x368	280x170

	0x0021881E: 0x7120F45F '_. q' - movs.w     a2, #0x280
	0x00218824: 0x71B8F45F '_..q' - movs.w     a2, #0x170

	0x00376214: 0x7120F45F '_. q' - movs.w     a2, #0x280
	0x00376218: 0x72B8F45F '_..r' - movs.w     a3, #0x170

736x416	2E0x1A0

	0x00218812: 0x7138F45F '_.8q' - movs.w     a2, #0x2e0
	0x00218818: 0x71D0F45F '_..q' - movs.w     a2, #0x1a0

[eboots.ZIP](https://github.com/Electry/VitaGrafix/files/2485965/eboots.ZIP)

**Comment by yaefeni1986** [comment]
Seeing all these game at native res would be great and can you help find the adress for gravity rush? Thanks for supporting electry

**Comment by Shinriji** [comment]
Great news. Hopefully they will be added on future updates.

**Comment by gensosuikoden** [comment]
Well done for finding those addresses. May I suggest you put the names of the games in the title of the post for the developer's convenience and quick reference.

Thanks

**Comment by FormerNoob** [comment]
The IB res.patch of these games have been added to the plugin' s code,so I should close the issue.

**Comment by Shinriji** [comment]
Dead or Alive Extreme Volleyball weren't added yet. You should reopen the issue until then.

**Comment by d0kterfreddy** [comment]
Nice work. I tried to mimic you're work. but I seem to be doing something wrong because the addresses I find are different. Could you possible look into Tokyo Xanadu? Its from the same developer and I think in the same engine. So I guess the resolution should be similar to find.
