### ISSUE TITLE
Borderlands 2 - 720x408 causes black screen

### ISSUE THREAD

**Issue by Electry** [Electry/VitaGrafix#119]
![black_screen](https://user-images.githubusercontent.com/12598379/47091323-f6702380-d224-11e8-93ff-72ad82de1841.jpg)

720x408 FB res. causes black screen glitches.
Also, screenshots can't be taken (resulting in "An error has occured" message).

**Comment by myrocode** [comment]
Same problem here.
I can confirm 640x368 works fine.

**Comment by Electry** [comment]
Here is an experimental patch that should fix 720x408 if someone wants to try.
I only did a very brief testing.
```
# Borderlands 2 [EU 1.07]
[PCSF00570,eboot.bin]
# Borderlands 2 [EU 1.07]
[PCSF00576,eboot.bin]
# Borderlands 2 [US 1.09]
[PCSE00383,eboot.bin]
@FB
1:0x24A94 uint32(<fb_w>)
1:0x24A98 uint32(<fb_h>)
# 32-align depth surface stride
0:0x36C6EC t2_mov(0,1,<if_eq,<fb_w>,720,736,<fb_w>>)
# Haxx force 736 stride for width=720 linear_strided textures
# B #-0x13D9E4 (0x8136C748)
0:0x4AA12C bytes(C2 F6 0C BB)
# CMP R8,#720
0:0x36C748 bytes(B8 F5 34 7F)
# BNE #0x4
0:0x36C74C bytes(00 D1)
# MOV R0,#736
0:0x36C74E t3_mov(0,736)
# MUL R4, R0, R3
0:0x36C752 bytes(00 FB 03 F4)
# B #0x13D9DA (0x814AA130)
0:0x36C756 bytes(3D F1 EB BC)
```

You'll need to replace the whole Borderlands section in patchlist.txt. Adding this to the bottom won't work.

**Comment by chrmichael** [comment]
It works, and GUI elements are readable (a significant improvement over 640x368) but certain textures have alignment problems. 
When boxes are opened for loot, the texture that is supposed to show the content is corrupted. There may be other problems. Will try to include screenshots.

**Comment by chrmichael** [comment]
I was on the right track - it turns out that replacing 736 values with 768 does the job, and fixes the texture corruption that I mentioned in the previous comment.

Thanks for coming up with a fix for 720x408!

**Comment by stuermera** [comment]
Hmm, doesn't work here... same black screen with artefacts :(

**Comment by chrmichael** [comment]
Great! 
Did you change 736 to 768?
It will remove some texture corruption that is present in the original fix from Electry
Regards,
Christian

**Comment by stuermera** [comment]
Worked. But when following Claptrap the game freezes. Happened two times. PSVita freezes for a minute and then switches off itself 🧐

**Comment by Electry** [comment]
Added in https://github.com/Electry/VitaGrafixPatchlist/commit/d3e434555acc1c494829db43bda43aaa044c98e2

Thanks for help/testing :)
