### ISSUE TITLE
[REQUEST] Ratchet Collection 60FPS hack

### ISSUE THREAD

**Issue by nad45** [Electry/VitaGrafix#123]
Hello
Is it possible to unlock the framerate? The games run pretty well at 544p event without overclocking     
Or it's not possible because the game speed also increases?

**Comment by Shinriji** [comment]
We really should make a thread with all those games with resolution and 60FPS issues so people (hopefully) won't stop ask for it.

**Comment by Babbosh** [comment]
Dear lord, read the previous issues. It's impossible to go on like this, same damn questions asked over and over.

**Comment by nad45** [comment]
Before asking, i searched in the previous issues but i didn't find the info
In which post it has been told that 60fps is impossible for Ratchet?

**Comment by BlackRayFox** [comment]
In 2.5 prebuild post
