### ISSUE TITLE
（Help）About Uncharted Golden Abyss！

### ISSUE THREAD

**Issue by yeqing1990** [Electry/VitaGrafix#125]
I tried to fix his EBOOT. I found a lot of 768x384 addresses. I tried to modify each code and found that many of them are the resolution of a single object: water, characters, plants. I modified it to 960x544 and the game was screened. There are other values ​​(768 select 384) that will give an error. Great God, what do you think?

**Comment by Electry** [comment]
added in https://github.com/Electry/VitaGrafixPatchlist/commit/14fe4e0064bc9e538496f44c2e24ecb6131be450
