### ISSUE TITLE
project diva f , Vitagrafix doesn't work...

### ISSUE THREAD

**Issue by neru264** [Electry/VitaGrafix#129]
Hello. I am Japanese. I can't understand English well.
so I use comments to translate.
It is the first time to use Github. I'm sorry if I was rude.

I installed Vitagrafix 3.1 and ioPlus using Autoplugin.
When I start up the game, 
"Patched
Internal:960x544
FPS cap: 60"
appears on screen.
However, the image quality did not improve and the FPS was still 30.
How can I get high image quality? 

Supplement
The Vitagrafix and ioPlus plugins are installed on ux 0: tai /.
There is no mistake in the description of config.txt.
My FW is 3.65 HENkaku ENSO.

**Comment by Electry** [comment]
Hi,

are you using NoNpDrm, official PSN game/cartridge, or maidump?
did you update the game to the latest version? If I'm not mistaken it is 1.01 for JP region.

**Comment by neru264** [comment]
thanks for the reply!
As you said, I was not updating the game version.After update, all plugins worked fine.Thank you very muchXD
