### ISSUE TITLE
Valhalla Knights 3 GOLD--resolution address

### ISSUE THREAD

**Issue by yeqing1990** [Electry/VitaGrafix#134]
![qq 20181102230559](https://user-images.githubusercontent.com/42913834/47953665-af6f8580-dfbb-11e8-9e75-40bbd2b89c3f.png)
I can only change this game to 720X408, and then the game is wrong. Do you have any other way?

**Comment by yeqing1990** [comment]
# Valhalla Knights 3 GOLD [JP 1.05]
[PCSG00307,eboot.bin,0x2A62D92D]
@IB
0:0x0C5840 t2_mov(1,3,<ib_w>)
0:0x0C584E t2_mov(1,6,<ib_h>)

**Comment by Electry** [comment]
added earlier
