### ISSUE TITLE
SOUL SACRIFICE Delta--Resolution address

### ISSUE THREAD

**Issue by yeqing1990** [Electry/VitaGrafix#135]
![qq 20181103230512](https://user-images.githubusercontent.com/42913834/47953793-340ed380-dfbd-11e8-9ce8-2a8aac7780f5.png)
I have tested 960x544 to run perfectly, but I can't find the address modified by FPS

**Comment by yimoduo** [comment]
> 您可以修改这个游戏只是用boot_config。 ini文件。
> 如果你安装了梅游戏:
> 1。 打开VitaShell
> 2。 boot_config开放。 ini ux0:app / PCSD00079 /资源
> 3. 找到“EffectGpuLimitThreshold”和“帧”,修改的数值60.0
> 4所示。 保存并退出。
> 完成了。
> 
> 如果你安装NND游戏,你必须使用repatch插件。

When revising this, it will be wrong when the book is turned over. I hope the great God can add the game.

**Comment by yimoduo** [comment]
> 您可以修改这个游戏只是用boot_config。 ini文件。
> 如果你安装了梅游戏:
> 1。 打开VitaShell
> 2。 boot_config开放。 ini ux0:app / PCSD00079 /资源
> 3. 找到“EffectGpuLimitThreshold”和“帧”,修改的数值60.0
> 4所示。 保存并退出。
> 完成了。
> 
> 如果你安装NND游戏,你必须使用repatch插件。

When revising this, it will be wrong when you turn over the book, or hope that the great God can add the game.

**Comment by yeqing1990** [comment]
@kofwinner 据吧友反应，修改文件会导致翻书有概率性报错，我帮他修改EBOOT文件后，他测试不在报错，所以希望作者能加进插件。不过我当时改这个文件没碰到报错的情况，我对比了两种修改方法，画面上的表现是一致的

**Comment by yimoduo** [comment]
> @kofwinner据吧友反应,修改文件会导致翻书有概率性报错,我帮他修改EBOOT文件后,他测试不在报错,所以希望作者能加进插件。不过我当时改这个文件没碰到报错的情况,我对比了两种修改方法,画面上的表现是一致的
[eboot.zip](https://github.com/Electry/VitaGrafix/files/2545567/eboot.zip)
求大佬修改下这个版本的灵魂献祭eboot，您之前发的是14M的

**Comment by yeqing1990** [comment]
@kofwinner 你去贴吧发百度网盘的地址给我吧 ，这个下载不下来

**Comment by yimoduo** [comment]
> @kofwinner 你去贴吧发百度网盘的地址给我吧 ，这个下载不下来

链接: https://pan.baidu.com/s/1N-A9NQQ-XP0_rtTe34KC1w 密码: 69u8

**Comment by yeqing1990** [comment]
@yimoduo   改好了。链接：https://pan.baidu.com/s/1dlsY4p8FGFlPYcnp5Euo3Q 
提取码：iz36

**Comment by yimoduo** [comment]
> @yimoduo改好了。链接:https://pan.baidu.com/s/1dlsY4p8FGFlPYcnp5Euo3Q
> 提取码:iz36

非常感谢大佬！

**Comment by molecopopo** [comment]
Can someone send this eboot? I can not download from this Chinese site

**Comment by yeqing1990** [comment]
@molecopopo I sent one night, but I do not guarantee that other areas can be used, please do the original file backup

**Comment by Electry** [comment]
Added to https://github.com/Electry/VitaGrafixPatchlist
