### ISSUE TITLE
Fate / EXTELLA LINK Report an error

### ISSUE THREAD

**Issue by yeqing1990** [Electry/VitaGrafix#136]
Open LOG.TXT
Title ID: PCSH10121
Found [MAIN] section, pos=0
Found [PCSH10121] section, pos=66
Patching seg000 : 006CEF98 to 4F F4 70 70, size=4
Patching seg000 : 006CEF9E to 4F F4 08 70, size=4

**Comment by Electry** [comment]
is it crashing? or what's the issue?

**Comment by yeqing1990** [comment]
@Electry
I found the problem. The version of my game is not up to date. Someone has tested it to run.
In addition: AC3 how do you solve it, NFS: MW is not the same problem, there is no way to solve
I sent you the resolution address of several games, I hope to help you.

**Comment by yeqing1990** [comment]
@Electry 
In the address you patched, I found VMOV R0, S0 Can you tell me his principle? It should work for many games that cannot be modified.
