### ISSUE TITLE
VitaGrafix bubble not showing up

### ISSUE THREAD

**Issue by KanonxTWGOK** [Electry/VitaGrafix#138]
I tried to install the latest version of VitaGrafix from both Autoplugin and from the manual way but nothing worked (ur0), the VitaGrafix bubble didn't show up (I'm using SD2VITA and mounted my memory card as ur0). I even had to reset taihen.conf and my Vita but still nothing happened.
PSVITA model: PCH-2000
Firmware: 3.68

**Comment by Electry** [comment]
it's only a plugin.

there is no bubble (unless you use something like [VitaGrafix Configurator](https://github.com/Kirezar/VitaGrafixConfigurator))
