### ISSUE TITLE
Does not Run

### ISSUE THREAD

**Issue by Codeman785** [Electry/VitaGrafix#140]
An Error Occured:
[string "?"]:190: cannot open requested file

Press X to restart.
Press O to enable/disable FTP.

Everytime I open vitagrafix this is what shows up ^ and I cannot do anything on this page.
Yes I'm running newest firmware, yes I did a clean install and deleted previous version files.
I have tried having the files in both ux0 tai and ur0 tai seperately, doesn't make a difference. Yes i have the plugin ioplus.
I have tried using the links from this website and from using autoplugin but nothing works at all. Ever since i started using sd2vita. Please help.

**Comment by FormerNoob** [comment]
Try to add a new folder  "VitaGrafix" in ux0:data/.

**Comment by teamjin** [comment]
I suggest you use 2.4 or earlier and download kuio instead of the ioplus plugin.
https://github.com/Rinnegatamante/kuio/releases

I would also suggest that you use kuio and VitaGrafix as the only running plugins for testing if it works (except from nonpdrm if you must).
