### ISSUE TITLE
Mortal Kombat [PCSB00106] resolution offsets

### ISSUE THREAD

**Issue by MinikPLayer** [Electry/VitaGrafix#143]
![image](https://user-images.githubusercontent.com/39161575/48304749-e6dfb400-e51e-11e8-85ce-f6d830fe4aad.png)
First one (0x812424BE) is in fight resolution, second one (0x812424C8) is menu resolution.

Game works, but UI isn't properly displayed

**Comment by SheidCraft** [comment]
UI offset is a known problem, the solution of which was never found, it is possible that the UI have about 640 * 480

**Comment by Electry** [comment]
I tried, but wasn't able to fix the UI, sorry.

I can add it anyway, if you want.

**Comment by MinikPLayer** [comment]
Until someone would find a way to fix the UI it's unusable so it's not worth adding

**Comment by nad45** [comment]
Maybe if we can find the UI file and replace it with the PS3 or PC version, it would solve the problem

**Comment by MinikPLayer** [comment]
Maybe it's possible, but not easy. Unreal Engine uncompress tool isn't working with PS Vita files so you would need to make new app to do this.

**Comment by Shinriji** [comment]
IMO they should add every game that it's possible, even if some bugs are eventually found.

**Comment by eddyfire** [comment]
Wouldnt mind to try it out if you can give us the patchlist config.. 😅

I believe injustice is by netherrealm studios as well.  Do u think u could do it @Electry?

**Comment by Electry** [comment]
![2019-02-16-021133](https://user-images.githubusercontent.com/12598379/52892209-aed8b480-3190-11e9-9bd6-0cd52c3d6898.png)

who tf is that XDD did I just break the game?

**Comment by ImplyingKinpatsu** [comment]
Dan Forden tbh

**Comment by Electry** [comment]
Oh, cool, never saw that easter egg before.

Anyway, I managed to stretch the UI to 408p/544p by overriding the viewport transformation (sceGxmSetViewport() call). I only did very little testing so if you encounter any issues please let me know.

![2019-02-16-025931](https://user-images.githubusercontent.com/12598379/52892869-0843e200-3197-11e9-9376-84fe221205d5.png)

Here is the patch for EU 1.00 (US later):

```
[PCSB00106,eboot.bin,0x2AA8AC12]
@FB
0:0x2424BE t2_mov(0,0,<fb_w>)
0:0x2424C2 t2_mov(0,1,<fb_h>)
0:0x2055F8 t2_mov(0,2,</,<*,<fb_w>,<fb_w>>,640>)
0:0x205600 t2_mov(0,3,</,<*,<fb_h>,<fb_h>>,368>)
```

**Comment by eddyfire** [comment]
Wow cool.. you're the man! Does this UI stretching method works for Injustice?

**Comment by SheidCraft** [comment]
[PCSE00023,eboot.bin,0xAB5E7564]
@FB
0:0x2424BE t2_mov(0,0,<fb_w>)
0:0x2424C2 t2_mov(0,1,<fb_h>)
0:0x2055F8 t2_mov(0,2,</,<*,<fb_w>,<fb_w>>,640>)
0:0x205600 t2_mov(0,3,</,<*,<fb_h>,<fb_h>>,368>)

**Comment by Electry** [comment]
I also found this flag **dword_81D928BC** which if you force-set to 0, the UI elements change position somewhat:

![2019-02-16-013040](https://user-images.githubusercontent.com/12598379/52902198-0406db80-320e-11e9-81c0-98c369454ec7.png)

No idea what is/was this used for. Perhaps during development?

**Comment by SheidCraft** [comment]
@Electry Is it possible to release a patch with flag dword_81D928BC which force-set to 0? because the game looks better and is more comfortable

**Comment by Electry** [comment]
The thing with MK9 is that every single tiny UI element (there are dozens) has hardcoded position (and size) in px distance from the top-left corner.

If we don't want to do any shenanigans with the viewport, we need to patch each of those values. They are all scattered throughout the eboot and finding them is very time consuming because there is no easy way to identify them (all within undocumented arm assembly code).

![2019-07-21-150212](https://user-images.githubusercontent.com/12598379/61591625-12945d00-abc9-11e9-82db-e4d59031e5b2.png)

Here I patched just a few of them and it is already 150+ lines of patchlist.txt code. There are a ton more, esp. if we also include the other game modes (TAG, multiplayer, etc...)

Other possible way would be figuring out how to transform/rescale the original surface without messing up the other 2d stuff that's there (smoke, blood, particles and so on...)

**Comment by SheidCraft** [comment]
I understand that just in 544p the game looks very good, even if the interface is shifted to the left.  and if playing with UI in the left corner is not very pleasant to play, then in this form it is quite possible.  It's a pity the interface is not in the middle.
![52902198-0406db80-320e-11e9-81c0-98c369454ec7](https://user-images.githubusercontent.com/42513747/61591906-b8999480-abd4-11e9-86e9-497dce515e96.png)

**Comment by nahob** [comment]
in what programm you open eboot.bin?

**Comment by nahob** [comment]
and what i should do with that txt
[PCSB00106,eboot.bin,0x2AA8AC12]
@FB
0:0x2424BE t2_mov(0,0,<fb_w>)
0:0x2424C2 t2_mov(0,1,<fb_h>)
0:0x2055F8 t2_mov(0,2,</,<*,<fb_w>,<fb_w>>,640>)
0:0x205600 t2_mov(0,3,</,<*,<fb_h>,<fb_h>>,368>)

**Comment by nahob** [comment]
@SheidCraft what i should do with that txt. i open eboot in emu8086
[PCSB00106,eboot.bin,0x2AA8AC12]
@fb
0:0x2424BE t2_mov(0,0,<fb_w>)
0:0x2424C2 t2_mov(0,1,<fb_h>)
0:0x2055F8 t2_mov(0,2,</,<,<fb_w>,<fb_w>>,640>)
0:0x205600 t2_mov(0,3,</,<,<fb_h>,<fb_h>>,368>)

**Comment by Electry** [comment]
> in what programm you open eboot.bin?

IDA Pro or Ghidra

> @Electry what i should do with that txt. i open eboot in emu8086

put it in patchlist.txt

please stop spamming, there is an edit button in the top right corner

**Comment by nahob** [comment]
@Electry  just create patchkist.txt? which folder should be stored this txt file?

**Comment by Electry** [comment]
Maybe you should read the [readme](https://github.com/Electry/VitaGrafix/blob/master/README.md) first.

**Comment by nahob** [comment]
okey and what i should write in config.txt

**Comment by nahob** [comment]
[PCSE00023]
FB=960x544
IB=960x544
FPS=60
MSAA=4x

?

**Comment by nahob** [comment]
![Kc8GLoab0Tw](https://user-images.githubusercontent.com/53262285/61799574-095af880-ae34-11e9-915c-ace89dafaf65.jpg)

ok it works but what can do whith HUD?

**Comment by nahob** [comment]
@electry answer pls i need your help

**Comment by Electry** [comment]
I made this a while back, but it isn't complete yet.
Place it in ux0:data/VitaGrafix/patch/
v5.0.0+ required

[PCSB00106.txt](https://github.com/Electry/VitaGrafix/files/4006414/PCSB00106.txt)

**Comment by stev88987** [comment]
Good job very smart :)

**Comment by Electry** [comment]
added in https://github.com/Electry/VitaGrafixPatchlist/commit/fe97d82cbd771a33373e8fe4d432d2348298ffa2

I did my best with repositioning and rescaling the UI, but there still might be some UI elements that I missed (I haven't tested story mode, only ladder/tag mode). If you find something that doesn't look right, let me know.
