### ISSUE TITLE
Sorry to ask, about Moto GP 14 US but no EU tweaks

### ISSUE THREAD

**Issue by SpamU47** [Electry/VitaGrafix#144]
Hi there, sorry to ask this dumb question. Just wanted to know why the plugin will work in Moto GP 13 for US and EU versions, but only in the US version of Moto GP 14. Just want to keep using my original cart (Moto GP14 EU) and save over 2gb, thanks a lot! This is awesome!

**Comment by Electry** [comment]
Because I don't own EU version nor did I find nonpdrm anywhere. If you send me dumped eboot.bin.elf of updated EU game, I can definitely add it.

**Comment by SpamU47** [comment]
> Because I don't own EU version nor did I find nonpdrm anywhere. If you send me dumped eboot.bin.elf of updated EU game, I can definitely add it.

Yes of course, sorry to reply so late. It's a NONPDRM backup of my own cart. I've checked for updates and found that the latest version is 1.01. How should I send it over? Thx a lot, I love this plugin!

**Comment by Electry** [comment]
Added to https://github.com/Electry/VitaGrafixPatchlist
