### ISSUE TITLE
World of Final Fantasy	PCSB00951 maybe others too

### ISSUE THREAD

**Issue by ChiSys** [Electry/VitaGrafix#15]
Effects are missing exg. gates don´t have yellow sign 
![2018-08-16-171110](https://user-images.githubusercontent.com/42444438/44217770-8687e300-a178-11e8-8fb9-fc2f4905a3ad.png) standart resolution
![2018-08-16-171728](https://user-images.githubusercontent.com/42444438/44217828-a61f0b80-a178-11e8-8bbb-50b354f7d450.png) 960x544

**Comment by ChiSys** [comment]
All effects are missing with 960x544 res. Other resolutions don't work the screen is distorted.

**Comment by Electry** [comment]
Try this. I made some changes.
[VitaGrafix.zip](https://github.com/Electry/VitaGrafix/files/2294251/VitaGrafix.zip)

**Comment by Electry** [comment]
You could try 800x480, that worked for me.

**Comment by ChiSys** [comment]
Can confirm that 800x480 works.

**Comment by RyuSeisuke1992** [comment]
I hav only blackscreen. how did you setup the 960x544?

**Comment by Electry** [comment]
Missing effects are related to insufficient RAM. After trimming the largest used memblock from 88 to 84 MB (freeing up 4 MBs) they appear to be working again (at 960x544).

It doesn't fix those distortions at other resolutions though.
