### ISSUE TITLE
Uncharted

### ISSUE THREAD

**Issue by molecopopo** [Electry/VitaGrafix#150]
Does anyone know in which resolution the uncharted golden abyss wheel? and is it possible in the future to apply a patch or is it practically impossible?

**Comment by ImplyingKinpatsu** [comment]
There are three other threads on this game.

**Comment by molecopopo** [comment]
Of course, but all unanswered. could you tell me which program you use to open the eboots?

**Comment by Babbosh** [comment]
@molecopopo If the other threads are left unanswered, what makes you think that you will get one here? 
My Lord, what a great mind.

**Comment by molecopopo** [comment]
Do you? If you are not willing to help, you do not have to comment.

**Comment by SheidCraft** [comment]
@Babbosh The guy thought that before him no one asked about Uncharted ... Although this game for some is a symbol of PsVita, and it is logical that many have long wondered about raising the resolution in this game😅

**Comment by SheidCraft** [comment]
@Molecopopo Here # 125 the problem is described in full detail.

**Comment by Babbosh** [comment]
@SheidCraft  he actually admitted that he saw the 125 issue but probably wanted to ask again because he looks like Adriana Lima and that would grant him an answer. 😂

**Comment by Electry** [comment]
added in https://github.com/Electry/VitaGrafixPatchlist/commit/14fe4e0064bc9e538496f44c2e24ecb6131be450

**Comment by Keivin1009** [comment]
Where's Japanese Version (PCSC00005) in patchlists?
