### ISSUE TITLE
[REQUEST

### ISSUE THREAD

**Issue by cdespo27** [Electry/VitaGrafix#157]
I would love to see NFS most wanted on a higher internal resolution and see how it stacks up against ps3 version specially since i think it uses some kind of AA technique.

**Comment by cdespo27** [comment]
I would love to see NFS most wanted on a higher internal resolution and see how it stacks up against ps3 version specially since i think it uses some kind of AA technique.

**Comment by Sprucuis** [comment]
Yes, I support it.

**Comment by Electry** [comment]
I would love it too
