### ISSUE TITLE
[REQUEST] Ratchet and Clank Collection

### ISSUE THREAD

**Issue by superwisemon** [Electry/VitaGrafix#16]
I would absolutely love to see these games run at native res, and given it runs perfectly fine at the resolution it does display at, it seems like it'd be fine performance wise with max clocks.

**Comment by Electry** [comment]
Game crashes when changing the res. to 960x544. Judging from the generated coredump, it goes out of memory (but I could be wrong).
Lowering the fb res. to 640x368 works just fine. Tested with Ratchet1 & Ratchet2.

**Comment by Electry** [comment]
As I suspected, it runs out of VRAM.

By lowering SceGxm parameterBufferSize I was able to save 4 MB and put it into the "Video" mem block of the game. I have no idea what implications this might have, but at least it boots now at 960x544.

![2018-09-07-151327](https://user-images.githubusercontent.com/12598379/45221524-fbe75f00-b2b1-11e8-864b-a3228ad7c93b.png)
![2018-09-07-152709](https://user-images.githubusercontent.com/12598379/45221737-a52e5500-b2b2-11e8-984b-344b0b1d05fa.png)


It has some issues with the UI though.

![2018-09-07-151408](https://user-images.githubusercontent.com/12598379/45221532-00ac1300-b2b2-11e8-8ca7-ca2f1ba6a54f.png)

This is Ratchet2, haven't checked the others yet.

**Comment by superwisemon** [comment]
Looks promising. Any chance we can test this with a build?

**Comment by ChiSys** [comment]
Awesome finding 👍 It seems the ui will render at native res but is displayed in the size of the default frame resolution.

**Comment by Electry** [comment]
Test build: [VitaGrafix_testbuild_v2.5.zip](https://github.com/Electry/VitaGrafix/files/2363789/VitaGrafix_testbuild_v2.5.zip)

It has:

Sly Cooper 1, 2, 3 FB + FPS patch (PCSF00269, PCSF00270, PCSF00271, PCSF00338, PCSA00095, PCSA00096, PCSA00097, PCSA00098)
Sly Cooper 4 FPS patch (PCSF00156, PCSF00206, PCSF00207, PCSF00208, PCSF00209, PCSA00068)
Ratchet & Clank 2 FB patch (PCSF00482, PCSF00485, PCSA00133)
Ninja Gaiden Sigma 2 Plus IB patch (PCSB00294, PCSE00233, PCSG00157)

Let me know if you encounter any issues.

**Comment by ChiSys** [comment]
Have played now from the first planet to the third planet in a row and didn't found something game breaking in Ratchet 2. Appart from some UI masking issues in the menues the game runs pretty sweet and looks really nice now. 
Little hint: Ingame hint messages can be disabled and if so you doesn't notice the issues while playing. Appart from the menues but they are all working and useable.
For me its acceptable and I hope you will look into 1 & 3 also.

Ninja Gaiden 2 works for me and I haven't noticed something is broken. Only loading times are feeling longer but I can be wrong.

Sly games working like a charm.

**Comment by TheMostEve** [comment]
Thank you @Electry this is best vita plugin ever
Oh god ninja gaiden 2 with better graphic and sly with 60 fps

**Comment by GitHubyoyo** [comment]
@Electry 
thanks author.This project is more interesting than games for me.
https://youtu.be/pPQM1IOdO5c

**Comment by nad45** [comment]
Thanks a lot for the test build @electry.
The game looks a lot better and still runs well without overclocking.
I hope you will manage to uncap the framerate.

**Comment by BlackRayFox** [comment]
Ninja Gaiden Sigma 2 Plus IB patch (PCSE00233, PCSG00157) crashes on boot

**Comment by BlackRayFox** [comment]
and for some reason sly 4 (PCSA00068) crashes in-game menu

**Comment by Electry** [comment]
I can only confirm PCSG00157 crashing. US Sigma2Plus and Sly4 are working for me.

**Comment by BlackRayFox** [comment]
Sly 4 no more crashing, but us sigma 2 keep throwing c2-12828-1 error

**Comment by BlackRayFox** [comment]
Okay i just checked config file, i have mistaken fb for ib
Sorry for bothering you

**Comment by ChiSys** [comment]
I have encountered a gpu crash in Ninja Gaiden 2. In Chapter six after playing, startet from chapter 3 and played in a row, weird graphical issues appeared and after that the gpu driver crashes. I could take a screenshot before crashing but I could not reproduce the bug yet. After rebooting everything works normal but I thought I should share the info anyway.

![2018-09-15-234111](https://user-images.githubusercontent.com/42444438/45596753-5de64980-b9c1-11e8-81d3-3707d437e899.png)

**Comment by TheMostEve** [comment]
@ChiSys
I already finished ninja gaiden sigma 2 from chapter 1 without any problem and i use loli con 500 mhz
Version PCSB00294

**Comment by lsd4me2** [comment]
if these games cant do native res why not try 840x476. would still be an improvement. (please do this!)
