### ISSUE TITLE
the game [persona4 the gold] use vitagrafix 3.2 can‘t working

### ISSUE THREAD

**Issue by seaonzone** [Electry/VitaGrafix#160]
gameid:pcsh00021 
use ver3.2 can't display disabled
but, use old ver2.5 is working 
helpme fix ths bug

**Comment by Electry** [comment]
Add

```
[PCSH00021]
IB=960x544
```

to *ux0:/data/VitaGrafix/config.txt*

**Comment by seaonzone** [comment]
> Add
> 
> ```
> [PCSH00021]
> IB=960x544
> ```
> to _ux0:/data/VitaGrafix/config.txt_

can not work
After adding (to ux0:/data/VitaGrafix/config.txt，[PCSH00021]
IB=960x544)
Plugin activation cannot be displayed after starting the game with version 3.2, but activation can be displayed in the upper left corner after starting the game with version 2.5.

**Comment by whinette** [comment]
works well there. Check that you haven't mixed ux0 and ur0?

**Comment by seaonzone** [comment]
thanks everyone, is done 
I changed mai to nnd version 
This plugin is working

**Comment by Electry** [comment]
yeah, the offsets in MAI are different from NND/original.
