### ISSUE TITLE
Next release??

### ISSUE THREAD

**Issue by eddyfire** [Electry/VitaGrafix#161]
Hey, you're really doing an awesome job. Just wondering, will there be any new updates coming up with more game support? Cant wait!

**Comment by Electry** [comment]
Yes, I'll make a new update soon with support for separate patch-list file. That way you won't need to update the plugin each time to get support for more games.

Res hacks for 8 more LEGO games are coming soon as well (added [here](https://github.com/Electry/VitaGrafixPatchlist))

**Comment by InitialXKO** [comment]
The author said it was a plan for the supported games codes move to config file so that everyone can add their games.
________________________________

**Comment by Electry** [comment]
https://github.com/Electry/VitaGrafix/releases/tag/v4.0-alpha.1

**Comment by Babbosh** [comment]
"Not the change in physics, movement, animation, speed". 
What?

**Comment by molecopopo** [comment]
The guy talking to himself haha

**Comment by kofwinner** [comment]
wrong ID in 
# Fate/EXTELLA LINK [ASIA 1.02]
[PCSG01091,eboot.bin]
it's PCSH10121

and there is not Resident Evil: Revelations 2 [ASIA 1.04]in config.txt or patchlist.txt
it's PCSH00187

**Comment by kofwinner** [comment]
Well~
Resident Evil: Revelations 2 [ASIA] is the same as JP
I did it myself ;)

**Comment by Electry** [comment]
@kofwinner 
So are the offsets for RE:R2 JP working for ASIA too?

**Comment by Babbosh** [comment]
> The guy talking to himself haha

@molecopopo  see? You are learning. At least now you realise that you usually write completely nonsensical posts and have the decency to delete them. 
Good kid, you have earned mum's subsidised internet subscription.
