### ISSUE TITLE
Miracle Girls Festival don't patch since 3.1

### ISSUE THREAD

**Issue by HixtyGamer** [Electry/VitaGrafix#165]
It's realy strange, that it stoped working. Previous versions of VitaGrafix patch this game fine.

**Comment by Electry** [comment]
You need to add the game to config.txt

```
[PCSG00610]
IB=960x544
```

**Comment by HixtyGamer** [comment]
That's not the case. I'm using VitaGrafixConfigurator.
I checked this file, and this lines was already there.
Also, Persona 4 and Diva games patch without any issues.

**Comment by Electry** [comment]
oh interesting, could you open ux0:/data/VitaGrafix/log.txt (using VitaShell) right after running the game?
Just copy & paste the "SELF path" here. It should be somewhere near the top in the log.txt. You'll need the latest v4.0

Also, does the OSD show at all?

**Comment by HixtyGamer** [comment]
Very strange...
This game doesn't appear in log.txt. Any other game appears, even if it not supported (testen on Mary Skelter Nightmare).
And no, OSD doesn't show up.

**Comment by HixtyGamer** [comment]
Actually, I just deleted this game and re-downloaded it from PKGj and it starts to work fine.
