### ISSUE TITLE
Ratchet and Clank Collection UI Bug

### ISSUE THREAD

**Issue by Carsonline1** [Electry/VitaGrafix#171]
So when I up the resolution, the UI messes up quite a bit when I tried RAC 3. You got any idea why? Btw thanks for all the work you do man, you are a life savor!

**Comment by Electry** [comment]
I mentioned it here: https://github.com/Electry/VitaGrafix/issues/121
No idea why yet.

**Comment by Electry** [comment]
should be good to go now, let me know if you encounter any issues
