### ISSUE TITLE
vita.txt file for IDA Pro 6.8

### ISSUE THREAD

**Issue by Doredialilligan** [Electry/VitaGrafix#179]
Hi :)
I've been following the steps here [http://psvita.chvila.sk/guides/getting-the-address/](url) but I can't create the vita.txt file.

Could someone share it? @Electry

**Comment by Sprucuis** [comment]
Hello there! Thank'u for link and about your problem, fresh vita.txt for you is here!
- [vita.txt](https://github.com/Electry/VitaGrafix/files/2949252/vita.txt)

P.S. sorry for long missing

**Comment by Doredialilligan** [comment]
Thank you so much!
The one that I have has 5170 lines. The one that you uploaded has 8611 lines. 
This will be really helpful :)
