### ISSUE TITLE
[Request] Phantasy Star Nova (PCSG00351)

### ISSUE THREAD

**Issue by DigiD2** [Electry/VitaGrafix#188]
Someone on [Baidu](http://dq.tieba.com/p/6032469951?pn=1) has found IB tweaks for the asian version. Wondering if anyone could find the IB for the JP version since the english patch works with that one. Thanks a ton to Sekiro :) and thanks a bunch to everyone who contributes,i do appreciate all your work.

You can click the link provided if your looking for the asian IB code.

**Comment by Electry** [comment]
added in https://github.com/Electry/VitaGrafixPatchlist/commit/5a1f7e7102c923894665fc33e9261d2812790e3e
