### ISSUE TITLE
[Request] Helldivers 

### ISSUE THREAD

**Issue by Stefan54** [Electry/VitaGrafix#191]
I love this game and it already does run kinda smooth in some situations when it's overclocked. But it first crashes all the time when overclocking, and second still suffers many framedrops in some situations with max possible overclocking, which is why I think it would be awesome if this game would be added here. I could imagine that lowering the resolution would improve it's performance a lot and make it more playable, without having to forcefully overclock it to max ;-;

**Comment by MatthewL2019** [comment]
here's the code for the resolution.
only  640 x 368 resolution works for this game.
runs about 50-60 fps without overclock.
still needs some overclocking to run at 60 fps stable.


`# HellDivers [6.00]`
`[PCSA00134,eboot.bin,0xEF98F6F3]`
`@FB`
`0:0x033FAC t2_mov(1,0,<fb_w>)`
`0:0x033FB4 t2_mov(1,3,<fb_h>)`

**Comment by Stefan54** [comment]
Yo man this is crazy! Thank you so much for your awesome work! I would like to share that if you don't mind, like on reddit & youtube. This is making the game so much more playable on the psvita & pstv, especially on hard levels with much enemies and more than 2 players. Again, thank you so much! Your work is very valuable!

**Comment by stev88987** [comment]
dude can you add eu 7.01 version please

**Comment by Electry** [comment]
Added in https://github.com/Electry/VitaGrafixPatchlist/commit/76a09f64827806f32c16a2653cc5b514ab2caded
Gave fixing 720x408 a try, and, I was able start and play the game, but it had some issues. Maybe some other time.
