### ISSUE TITLE
force 30fps on default 30fps game is good?

### ISSUE THREAD

**Issue by HighPingTek** [Electry/VitaGrafix#194]
change something if I use the vitagrafix limiter to lock fps at the same value of the game? eg better frame time or less input delay, like rivatuner on pc?

**Comment by EnekoT2001** [comment]
Idek but the safest option is just not activating nothis (+ some games with locked 30 run at 60fps on menus and stuff so...)

**Comment by Electry** [comment]
VitaGrafix doesn't limit the fps, the games do, VG just modifies how they do it, so no, it won't be of any benefit. If you want 30 fps and 30 fps is the default, you should set it to FPS=off
