### ISSUE TITLE
Minecraft update produces error in vitagrafix 

### ISSUE THREAD

**Issue by keydead** [Electry/VitaGrafix#195]
Hi im trying minecraft, and VitaGrafix say mi title is not supported please update your game. but i have the last update 1.83 released on March 19, 2019 

sorry for my English

**Comment by mrdivdiz** [comment]
https://github.com/Electry/VitaGrafixPatchlist/issues/46#issuecomment-476031551 - this may help

**Comment by Electry** [comment]
Updated in https://github.com/Electry/VitaGrafixPatchlist/commit/ca9d6aaafd93d9f8268f7887aba21f8b0214842c
