### ISSUE TITLE
[Request] Lumines: Electronic Symphony 60fps

### ISSUE THREAD

**Issue by Dupdon** [Electry/VitaGrafix#196]
Hi guys, great work with the plug in, been enjoying Jak and Daxter at 30fps recently and its worked like a charm!

I love lumines and it would be great to see a 60fps patch for it. Thanks!

**Comment by q6164007** [comment]
```
# Lumines Electronic Symphony  [US 1.01]
[PCSE00009,eboot.bin,0x870C9A3D]
@FPS
0:0x929D0 t2_mov(1,0,<vblank>)
```

**Comment by Dupdon** [comment]
Thanks I'll give this a go when I'm home! I'm using the EU version so will the code be different?

**Comment by q6164007** [comment]
```
# Lumines Electronic Symphony  [EU 1.02]
[PCSB00061,eboot.bin,0x805B6438]
@FPS
0:0x929F4 t2_mov(1,0,<vblank>)
```

**Comment by Dupdon** [comment]
Tried it and it works great thank you! Is there any way to tweak the other graphical settings with this title?

**Comment by q6164007** [comment]
No, but the game itself works very well. It runs at 960x544 resolution and 4x MSAA.

**Comment by Andrey446** [comment]
stupid question, but where should these codes be copied?

**Comment by Electry** [comment]
added in https://github.com/Electry/VitaGrafixPatchlist/commit/889f3d6221cd61d016d6c9f2b343ec3c65b7f1a4
waiting after fb is set, instead of before, fixed the fps drops
