### ISSUE TITLE
no output ingame?

### ISSUE THREAD

**Issue by kane159** [Electry/VitaGrafix#2]
im using nonpdrm version of this game PCSH00021 the menu and whatnot shows but other then that is black , is this plugin not support NoNpDrm version?
my sysuem 3.68 with h-encore
heres how it looks
https://imgur.com/Bj97BxE

**Comment by Electry** [comment]
I made small counting error. Uploaded v1.3.1, please try again.

**Comment by kane159** [comment]
it work! thank you very much
https://imgur.com/5P7HZGt
