### ISSUE TITLE
 will bring more games as if sports, anime and cartoon? thank you very much for your great work @Electry, I think you are an amazing person and I thank you for everything you are doing at sena vita vc and an inspiration for me, if one day I managed to do something so great and useful for vita I owe everything to you

### ISSUE THREAD

**Issue by Sal-gamer** [Electry/VitaGrafix#202]
please continue the project for months and months that you have not brought anything new

**Comment by SheidCraft** [comment]
I don’t think it’s worth waiting for updates.  Alas, this project is rather dead than alive.  I was hoping for Uncharted in 544p or Mortal Kombat, but we won’t see the first one, and in the second there is a problem with animation displacement

**Comment by seishinn02** [comment]
Would be good if this gets continued.
Or at least would be thought on how to add things on patchlist

**Comment by Littlesquee90** [comment]
He added native res for The Legend of Heroes (Jap) about 3 days ago... A lifeline!

**Comment by Sal-gamer** [comment]
He continued the project but I want more games

**Comment by Sal-gamer** [comment]
@Electry tells me will you bring more games? And more resources? And more optimization? What's new in the ps vita scene?

**Comment by Sal-gamer** [comment]
@Electry  puts 2x and 4x MSAA on unchaetd and other games other than ned for speded??

**Comment by Girotin** [comment]
@SheidCraft actually if you see the patchlist, you can use Vitagrafix with Mk and Uncharted with some extra settings.

Mk gets waaaay better at 960x544,
But Uncharted gets unplayable, no matter the resolution you try, keep the default one works better

There is one for Gravity Rush too, you can find the command lines somewhere here in the issues topic, but it has some graphical glitches, but besides that, it turns into a new and gorgeous game at 544p

Search for the readme and you can find the steps, it's actually very easy to setup

**Comment by Sal-gamer** [comment]
@ Sheidcraft, First, I was talking about the MSAA filter 2x and 4x without resolution. I want to remove the interlaced lines (with closed lines) and not increase the resolution. I know the games in which he is doing his excellent job, but I want more games, like sports, golf, futbool, etc. ... sports games are minimal and minimal, all exclusive to ps vita, even those that are no longer exclusive initially, Assassins Creed 3 Revelation needs adjustments to FPS and MSAA 2x or 4x. and asked if he would bring news about the vita scene. And the gravity rush, I want it to be playable at 960x544 with MSAA 4x or 2x, FPS 60, maximum resolution, high and stable rate and without the tangle of line (closed), or at least the gravity rush at 960x544, I want to ask them to bring those features to every game, knowing that the job is difficult, but it would be amazing if the games had 2x or 4x MSAA, maximum resolutions and high FPS rate. second, please read what I wrote correctly, you answered something that had nothing to do with me. Third, if you have any "gravity rush" news set by someone else and you want to make it available, I accept, but, except with a ghost, only make it available if someone finishes before Electry and is 100%
