### ISSUE TITLE
[Request] RE Revelations 2 Asia ver (PCSH00187)

### ISSUE THREAD

**Issue by kofwinner** [Electry/VitaGrafix#207]
RE Revelations 2 Asia ver (PCSH00187) is the same as JP ver (PCSG00594),but not in the official patchlist.
Would you please add PCSH00187 into the official patchlist.
So that I don't need to modify patchlist every time.

> #Resident Evil: Revelations 2 [JP 1.04]
> [PCSG00594, eboot.bin, 0x1AF1E91B]
> #Resident Evil: Revelations 2 [AISA 1.04]
> [PCSH00187, eboot.bin, 0x2302049E]
> @IB
> 0:0xCCFF3A t2_mov(1, 1, ib_w)
> 0:0xCCFF42 t2_mov(1, 1, ib_h)

**Comment by Electry** [comment]
Launch the game, open VitaShell, open ux0:data/VitaGrafix/log.txt and copy/paste here the module NID.

**Comment by kofwinner** [comment]
> Launch the game, open VitaShell, open ux0:data/VitaGrafix/log.txt and copy/paste here the module NID.

Thank you! I've got the NID: 0x2302049E
It works!

**Comment by Fershock** [comment]
Hi electry, one question, have you thought about working on the Native Resolution for PSP games on PSVITA project?  I think you are one of the most talented people in the psvita scene and I think you could do it.  Also if you complete it they give you a remuneration of 700 dollars
