### ISSUE TITLE
[Question] Framebuffer & Internal Buffer

### ISSUE THREAD

**Issue by greggameplayer** [Electry/VitaGrafix#21]
can we set these to 1280*720 ? because the ps tv can handle that resolution.

**Comment by greggameplayer** [comment]
@Electry why ?

**Comment by Electry** [comment]
you could try setting the internal res above 960x544, but even if that had worked, it would still be downsampled to 960x544 and then back upscaled to whatever res your ps tv outputs (720p/1080p).

**Comment by greggameplayer** [comment]
@Electry but the quality will be better even if it's downsample ,right ?

**Comment by Electry** [comment]
It would be nice, but it is beyond my knowledge :/
