### ISSUE TITLE
VitaGrafix generates screenshot's error

### ISSUE THREAD

**Issue by StormSora** [Electry/VitaGrafix#216]
Actually notice this error recently. Have no ideia why this is happening, but if vitagrafix is enabled I can't take screenshots, it notifies an error saying "An error has occured" and doesn't save the image. However, it cretes a folder reffering to the original image in ux0:/pictures/SCREENSHOTS without anything inside, not even a corrupted file.

Would really appreciate if you fix it or teach me how to fix it on my device.

Here's a video showing it:
https://youtu.be/mrQuMCnYY4s

**Comment by Electry** [comment]
This has never happened to me. VitaGrafix doesn't run in SceShell. Are you sure it is related to it?

**Comment by StormSora** [comment]
Yeah, the screenshots works when VitaGrafix is disabled in ur0:/tai/config.txt, otherwise I receive the error message... The screenshot folder is created, but the image itself isn't due to the error. Already tried to reinstall VitaGrafix a couple of times removing even the data/VitaGrafix folder, but the error persists. Any ideia of how to fix it? Maybe is an error on my device...

**Comment by StormSora** [comment]
Actually I've found this too... I can't take any pictures on my vita, not even on the camera, when I have VitaGrafix enabled. I got this error (C2-10828-9) when I try to take photos and have no ideia how to fix it (actually did research on the internet, didn't found any clue). How ever, for whatever reason, I can record videos on Vita...
![IMG_20200218_145755](https://user-images.githubusercontent.com/61165187/74764249-20de5080-5260-11ea-8139-e33df48d2994.jpg)

**Comment by StormSora** [comment]
Actually it seems to happened due to a corrupted sd2vita plugin that when VitaGrafix was active at the same time with it doesn't allow any image to be generated. It was resolved by reinstalling sd2vita plugin.
