### ISSUE TITLE
[Request] Need For Speed: Most Wanted

### ISSUE THREAD

**Issue by JuanD817** [Electry/VitaGrafix#22]
Could you make a resolution and/or 60fps patch for Need For Speed Most Wanted?

**Comment by Lordjontan** [comment]
Yes, please

**Comment by RadiantAnsel** [comment]
A petition I want to back it up if the game is actually possible to make it

**Comment by EulenCarbon** [comment]
To be honest，stable 30 FPS is quite enough （at least for me），so I think the resolution is the point.
Criterion Games actually did a nice job， but we just can't stand the  pixelated headlights anymore.

**Comment by nad45** [comment]
The resolution can be lowered but not upscaled, the game crashes.

**Comment by Haasman0** [comment]
> @Electry To be honest，stable 30 FPS is quite enough （at least for me），so I think the resolution is the point. Criterion Games actually did a nice job， but we just can't stand the pixelated headlights anymore. If you need the eboot， take it. Keep it up! [eboot.zip](https://github.com/Electry/VitaGrafix/files/2320345/eboot.zip)

@EulenCarbon How did you fix the headlights, can you make a patch for EU version please
