### ISSUE TITLE
JP ver. of WoFF elf uploaded!

### ISSUE THREAD

**Issue by NickRoxNRX** [Electry/VitaGrafix#25]
Pretty please? :)

I'd be happy to send you the eboot if necessary!

**Comment by Electry** [comment]
Sure, send me eboot.bin.elf please

**Comment by NickRoxNRX** [comment]
Here's the link to the JP eboot.bin.elf :3 Thank you!!

https://www.dropbox.com/s/yyezoz0gsxx4y7a/JP-WoFF-ELF.zip?dl=0

**Comment by Electry** [comment]
Added
