### ISSUE TITLE
VitaGrafix doesn't apply anything

### ISSUE THREAD

**Issue by paj1s** [Electry/VitaGrafix#257]
I want to set higher fps cap in jak and daxter for example, i do it and click save, it does say saved but it stays locked on 20fps.
I tried to:
-reinstall plugin
-install it on both of my vitas (1000 model with sd2vita and 2000model with sdcard)
-reset both vitas and do a clean install of absolutely everything including the jailbreak (i wasn't doing this because of vita grafix)
-restart
-another games
-different region game

I don't know what to do, i have installed vitagrafix following the instruction found here on the wiki before the reset, now i have installed it using autoplugin and it still doesn't work, please help.

**Comment by KutsuyaYuki** [comment]
Do you see the overlay with the FPS you set it when you start the game, if not, are you sure you set the proper settings in Vita Grafix Configurator?

Are you sure you have the correct version of the game for patch you are using?

**Comment by paj1s** [comment]
The plugin seems to be working i can contol the overlay using select and up/down arrows also i can set the overclock (i don't know if it has any effect) but i can mess with the settings. I will check if the versions are in match but it should be, the game never received an update as far as i know.

Proper settings? well i just clicked on enabled both in vita grafix and the game + i increased the fps cap to 30 and clicked save on both.

**Comment by paj1s** [comment]
Nevermind lol, i fixed it, i don't know how but i was messing with it and it just works now, thank you very much.
