### ISSUE TITLE
config.txt file

### ISSUE THREAD

**Issue by justalex95** [Electry/VitaGrafix#259]
Apologies for posting here, but I have checked for an hour trying to download a config.txt file for vitagrafix without success. I know this isnt an issue but could anyone upload their config.txt file?

I'm using it with vita3k and vitagrafix doesnt work properly so doesnt produce a config.txt file. I dont know what formatting the config.txt file uses but would like to try and see if the patches will work with vita3k as alot of games are limited to 30 fps

apologies again for posting in the issues section but I couldnt think of a better place to post, if anyone can help I would really appreciate it, thanks

**Comment by KutsuyaYuki** [comment]
Hey there, I'm not sure it'll work, but I'll upload mine tonight for ya.

**Comment by justalex95** [comment]
brilliant, thanks very much. its always worth a try, especially if later versions support plugins like thread optimiser

**Comment by KutsuyaYuki** [comment]
[config.txt](https://github.com/Electry/VitaGrafix/files/12643050/config.txt)

This is the config file I use on my vita, it's not a 'default' file by any means!

**Comment by justalex95** [comment]
yeah, does not work. its a shame, playing games at over 30fps was easily doable and now the emulator cant do something the original console could... supposed to be the other way round haha.

anyway thanks for the config file, much appreciated

**Comment by KutsuyaYuki** [comment]
Yea, the emulator doesn't really emulate the hardware, just the software, hence that's why it doesn't work.
