### ISSUE TITLE
[request] Mortal Kombat Komplete Edition

### ISSUE THREAD

**Issue by Charlieeco95** [Electry/VitaGrafix#27]
Could you please add support for Mortal Kombat Komplete Edition [PCSE00023], please?

Thank you so much in advance!  Your plugin is super awesome!

**Comment by Electry** [comment]
I can, if you don't mind that the HUD doesn't stretch.

https://www.reddit.com/r/vitahacks/comments/7phk3d/mk9_native_resolution_hack/
https://i.imgur.com/2bj00F6.jpg

**Comment by SheidCraft** [comment]
I tried to find HUD in game textures and models, but found nothing. I think it's worth taking a closer look at eboot to increase the HUD, or at least slightly shift them to the right or the middle

**Comment by Charlieeco95** [comment]
@Electry 
I don't mind that HUD doesn't stretch.   Thank you so much for your hard work~  please add it~

@SheidCraft   yeah,  that would be great if HUD can slightly shift to the middle.

**Comment by RadiantAnsel** [comment]
This is great already, just make the HUD beeing in the center and the power bars beeing in the down side, I don't mind if they look smaller that what they should.

**Comment by Electry** [comment]
US region added in https://github.com/Electry/VitaGrafixPatchlist/commit/b35ff59f3648c264f3d7c1317a1e76a03fb8a2a1
