### ISSUE TITLE
That's amazing！

### ISSUE THREAD

**Issue by mikasha171** [Electry/VitaGrafix#30]
Good plugin! Can you support “NINJA GAIDEN sigma2 plus( PCSB00294)”now? May I send EBOOT to you？thanks.

**Comment by mikasha171** [comment]
The resolution of this game does not seem to be 960× 544. even if it uses overclocking, its frame number is not very good. so can you improve its resolution and frame number? I think it should be 60 frames.
If you can, thank you in advance.⊙▽⊙

**Comment by ImplyingKinpatsu** [comment]
Ninja Gaiden Sigma 2 already has a variable resolution in place. Making the game have a 60FPS cap when it has no chance of hitting it will cause needless framepacing issues

**Comment by mikasha171** [comment]
Really? That's really disappointing. although the resolution of sigma 2 will reach 544 p, it still looks far worse than sigma 1. the scene has a lot of serrations. Frame number problem, 60 fps will lead to game error? Or is the ceiling 30 frames? Have you already tested it? I really hope that the number of frames can be improved, even if the resolution is not 544 p, it doesn't matter. lol

**Comment by Electry** [comment]
@ImplyingKinpatsu nah, sigma 2 plus won't reach 544p, only 864x480.

Closing this in favor of #53
