### ISSUE TITLE
[Request] Wipeout 2048

### ISSUE THREAD

**Issue by ExtremeCaliber** [Electry/VitaGrafix#31]
I believe the game has variable resolution which may make it more difficult. I've been trying to learn how to do upscales myself following this pastbin: https://pastebin.com/YHL6i4vA. The game I'm trying to edit was Gravity Rush. However, I got lost after step 8 when it said to paste the converted code at the offset given. I don't quite understand where to paste it. (I don't know much about hex editing, I'm using HxD) I just want to make sure I'm not doing anything wrong.

**Comment by Instandhaltung** [comment]
Overclocking the vita already greatly improves the resolution, especially for the HD/Fury packs. I haven't noticed significant downscales since I overclocked.

**Comment by ExtremeCaliber** [comment]
Hmm I suppose I'll try it overclocked. I haven't tested the game while overclocked yet but I always assumed it wasn't running native. But ty for the info

**Comment by Instandhaltung** [comment]
Yeah, it especially fixes the weird behaviour that the HD tracks are super low res at the beginning of the race:
Normal speed:
![2018-08-20-205046](https://user-images.githubusercontent.com/20743229/44361375-f4584580-a4bd-11e8-8ea4-bfa1d3152623.png)
Overclock:
![2018-08-20-205004](https://user-images.githubusercontent.com/20743229/44361374-f4584580-a4bd-11e8-942e-7bbe3381a4e0.png)

**Comment by Shinriji** [comment]
Nice. Even if there is some drawbacks, I'd like to see what is a 60FPS wipeout 2048 could be. Zone mode on 60FPS should be amazing.

**Comment by EnekoT2001** [comment]
Btw is there any way to change/deactivate the MSAA now (since VG now supports MSAA patching)?
I know this is a super old thread but still, it would be interesting

**Comment by djhazardous** [comment]
Would a 40FPS lock be possible to implement with this game? 40 offers a big noticeable improvement over 30 and since 60 stable is not possible (even with overclock and resolution downscaling) it would be a nice middle ground.
