### ISSUE TITLE
[Question] What happens if you install VitaGrafix while already having a modified eboot?

### ISSUE THREAD

**Issue by ExtremeCaliber** [Electry/VitaGrafix#36]
I already have Dead or Alive+ on my Psvita with it's eboot changed. Are there any side effects if I were to install VitaGrafix with a modified eboot?

**Comment by diegorocha2007** [comment]
Yeah, I was wondering the same, I have a Ridge Racer eboot changed

**Comment by ExtremeCaliber** [comment]
Alright sweet ty
