### ISSUE TITLE
Crash Borderlands 2 config.txt

### ISSUE THREAD

**Issue by jemorganise** [Electry/VitaGrafix#38]
Hey hey! First thank for your work! So I have a crash error when I start the game and when data/Vitagrafix/config.txt is in ux0. When not, the game launch correctly with this message up "PCFS00570: disabled". I try config.txt in ur0 but nothing happens.

**Comment by superwisemon** [comment]
Make sure you have the latest version of Kuio. Versions earlier than 1.2 cause a crash using the config.

**Comment by Electry** [comment]
do you have your game updated to 1.07?

**Comment by jemorganise** [comment]
Yes, 1.07 installed. And little Dlc for have some character, they have 2 big Dlc that I didn't installed yet, must try?

**Comment by Marioh2451** [comment]
i think is sd2vita in ux0, same thing happens to me. Installed kuio and vitagrafix in autoplugin, it doesn't make a data config file in ux0, i made it myself and doesn't work. Any solution for sd2vita users?

**Comment by superwisemon** [comment]
It's not sd2vita, I'm using it mounted as ux:0 just fine alongside the config.

**Comment by Marioh2451** [comment]
could u pass me config.txt file please? Can't open readme.md in mobile

**Comment by soulloster** [comment]
it is pointless，i thik，because i didnot find any differences between 960x544and640x398. resolution and framerate didn't chang visually

**Comment by superwisemon** [comment]
The game runs a lot smoother at 640x368 and looks noticeably worse, so I imagine that you haven't managed to get it working properly. Additional changes to the ini files makes the game a constant 25-30fps experience rather than 15-25fps

**Comment by soulloster** [comment]
maybe you are right ,but i can see a line of wards that ([PCSE00383]patched 
   framebuffer640x368)when game boot,this is cont of config.txt
[MAIN]
ENABLED=1

[PCSE00383]
FB=640x368
game v1.00 if you think something incorrect,place tell me ok .

**Comment by Electry** [comment]
@soulloster Updated game has different offsets (iirc), so you should update to the latest game version.
