### ISSUE TITLE
[REQUEST] Ys: Memories of Celceta

### ISSUE THREAD

**Issue by ChiSys** [Electry/VitaGrafix#39]
Would be great if you can look in to game.

**Comment by Electry** [comment]
After a quick try I couldn't get this to work.
I found some 720x408 float MOVs aswell, but after patching the game just crashes.

@NickRoxNRX

![2018-08-25-035027](https://user-images.githubusercontent.com/12598379/44614101-ffdda080-a81e-11e8-958c-82b87f72e791.png)

**Comment by ChiSys** [comment]
Thanks for trying and your effort.

**Comment by Electry** [comment]
let's leave it open

**Comment by Electry** [comment]
![2018-10-21-175648](https://user-images.githubusercontent.com/12598379/47270070-a798f580-d566-11e8-916d-e2ffec47da90.png)

I can't get this last thing (that blurred, barely visible part) to stretch horizontally. For some reason it fills 544px height, but is stuck at 720px width. I went through every single '720' reference (float/int movs, data section, etc...) in the eboot, without any luck :(

**Comment by Shinriji** [comment]
Even so, it's way better than the original. You should implement it. 

Sucks that the US and EU version didn't get the JP patch that increased the draw distance.

**Comment by Electry** [comment]
No, I haven't added anything yet (to the build).

**Comment by beanbeany** [comment]
This game shows up in the build but when I set the graphics to 960x544 it says it default and refuses to change. Any advice?

**Comment by Electry** [comment]
added in https://github.com/Electry/VitaGrafixPatchlist/commit/b134dc6f840c3abb31a91b207a4e8b47d38192db

fixes in
https://github.com/Electry/VitaGrafixPatchlist/commit/262f4a4de516a576253335d0fcecd9894e3c2ffa
https://github.com/Electry/VitaGrafixPatchlist/commit/53f06ac9750fb927eb611ca6b51987dbc99bf324

**Comment by adrianbass360** [comment]
Hey Electry. Is there a reason why the JP version shows an error on line 1571? =/
