### ISSUE TITLE
[Request] Uncharted Golden Abyss

### ISSUE THREAD

**Issue by SheidCraft** [Electry/VitaGrafix#41]
I was delighted from your modifications for God of War and Jak&Dexter. and I interested in question. It possible to ever see Uncharted in native resolution?

**Comment by Errol1886** [comment]
Native resolution support for this game would be great.

**Comment by Electry** [comment]
added in https://github.com/Electry/VitaGrafixPatchlist/commit/14fe4e0064bc9e538496f44c2e24ecb6131be450
