### ISSUE TITLE
[Request] donations

### ISSUE THREAD

**Issue by Babbosh** [Electry/VitaGrafix#47]
Please accept donations. You have no idea what you are doing for a fan of racing games like me who is always, for job reasons, on the move and Vita is the only (amazing and credible) option. 
The work you did for WRC4, Asphalt and Ridge Racer, It is amazing! And Killzone full res 60fps too!

**Comment by Electry** [comment]
WRC4, asphalt and ridge racer were already discovered before. Killzone 60fps doesn't really work very well.

**Comment by Babbosh** [comment]
Well I am not gonna pest you to give you money but the right to decide should be given to the one who receives the good. 
I was struggling with modded eboots and most of the time I couldn't find the right one. This plugin made things work and easy to do. 
Well, you don't want my money than accept my deepest congratulations.

**Comment by Electry** [comment]
Thanks, perhaps later, when there will be more games supported.

**Comment by Babbosh** [comment]
Ok then.
