### ISSUE TITLE
【Request】Ninja Gaiden Sigma 2 ＋

### ISSUE THREAD

**Issue by mikasha171** [Electry/VitaGrafix#53]
The resolution of this game does not seem to be 960× 544. even if it uses overclocking, its frame number is not very good. so can you improve its resolution and frame number? I think it should be 60 frames.
If you can, thank you in advance.⊙▽⊙

**Comment by EulenCarbon** [comment]
That‘s gonna be perfect if it's 60 fps，here is the eboot.


[eboot of Ninja.ZIP](https://github.com/Electry/VitaGrafix/files/2320333/eboot.of.Ninja.ZIP)

**Comment by mikasha171** [comment]
Hey, it seems that the author doesn't want to talk to us lol.
Perhaps Sigma 2 does not support it....

**Comment by playerlilin** [comment]
Maybe the author kept busy about other games.I'm really looking forward to see this game run 60 fps on psvita.Even though this game has some issues,it still my favorite ACT game on vita.

**Comment by gittyno1** [comment]
I agree, this game is fantastic, i had so much fun, but as many vita games ,30fps just makes it unpleasant for eyes and makes it look like emulation instead of native...idk thats how i felt when playing. j remember from time to time i thought to my self "i wish this is in 60fps"...

**Comment by mikasha171** [comment]
l gave up

**Comment by playerlilin** [comment]
Don't be so passtive.The author hasn't been showed up in this issue.So be patient and wait for author will say.Even this game won't be running 60 fps on vita,I still want to know the reason.

**Comment by Babbosh** [comment]
I agree.  This game would be amazing with the FPS cap removed!

**Comment by Electry** [comment]
I can't do 60 FPS as the game speed increases when uncapped. Slowdowns can also be seen when you set the GPU clocks to something low (55 or 111 MHz) to limit the FPS.

As for resolution, it uses dynamic scaling with 3 "presets" and jumps between them based on the framerate. 864x480 being the highest res., 640x416 the middle and 384x384 the lowest.
We can just set all these 3 presets to 960x544 and it will always run at 960x544, eliminating the dynamic scaling.

**Comment by mikasha171** [comment]
First of all, thank you very much for your reply. I really like this game, so I have been waiting for your reply, I read your instructions, that is to say 60 fps can not be achieved, but the resolution 960x544 is achievable?
The porting of this game is really bad, but it is also the most fun action game on PSV, I always like it.

**Comment by gittyno1** [comment]
to bad, 60fps would look great on vita

**Comment by yeqing1990** [comment]
That's good news.

**Comment by Babbosh** [comment]
IB full res, it's still a great achievement.

**Comment by Electry** [comment]
Until I add it to proper release, you can try test build posted here: https://github.com/Electry/VitaGrafix/issues/16#issuecomment-419675920

**Comment by mikasha171** [comment]
Thank! I'll test it now！

**Comment by yeqing1990** [comment]
GOOD！

**Comment by kofwinner** [comment]
@Electry 
Thanks bro!Good job!
Now I have tried VitaGrafix_testbuild_v2.5,it can't work on Ninja Gaiden Sigma 2 Plus (PCSG00157) in my PSVita,but it can work on PCSB00294.
Also there is a problem:I use this plugin LOLIcon:[https://github.com/dots-tb/LOLIcon](url),then overlock to 500mhz.When I open Ninja Gaiden Sigma 2 Plus,it gets stuck on the TECMO logo.But if I use VitaGrafix v2.4,it works fine.

**Comment by Electry** [comment]
Thanks for reporting.
I made a spelling mistake in the "PCSG00157" title id check and so it tried to patch invalid address (therefore crashing). I will fix it in the next (test)build.

I haven't tried LOLIcon yet. Did you try other games as well? or is it just Ninja Gaiden?

**Comment by kofwinner** [comment]
OK!
I tried again, the Ninja Gaiden Sigma 2 Plus getting stuck on the openning TECMO logo.Then I found it caused by another plugin.When I shut it down,the game works fine.

**Comment by ChiSys** [comment]
#https://github.com/Electry/VitaGrafix/issues/16#issuecomment-421761974
