### ISSUE TITLE
[REQUEST] The Sly Collection

### ISSUE THREAD

**Issue by Cooper941** [Electry/VitaGrafix#55]
Uncap FPS for 60fps please?

**Comment by Electry** [comment]
Sly 1 was added. The other ones run at 960x544 native. I will check if 60fps is possible for them later, but (at least) Sly 2 and 3 should be similar to 1.

**Comment by TheMostEve** [comment]
Thank you for Sly 1, next update unlock 60 framerate for sly 2,3 and 4 please

**Comment by ChiSys** [comment]
Can you look at this version to 
[[PCSF00338].zip](https://github.com/Electry/VitaGrafix/files/2342737/PCSF00338.zip)
By the way played the game now for 2 hours and had no errors so far.

**Comment by Electry** [comment]
I added test build here: https://github.com/Electry/VitaGrafix/issues/16#issuecomment-419675920
