### ISSUE TITLE
[Request] Spiderman 30FPS lock

### ISSUE THREAD

**Issue by nad45** [Electry/VitaGrafix#62]
The framerate is really unstable in this game, especially in town.
Could you try to lock the framerate please?

**Comment by gittyno1** [comment]
EDIT:

I got PC version running @60 FPS, and since PC version is a port of a Vita version (the original one), i presume developers INTENTIONALLY locked FPS not to go above 30 FPS, because you know, battery i presume...
But i believe it can go to 60 FPS if just unlocked! 

The game would look so much better @60 FPS!

Thanks in advance! :)

**Comment by gittyno1** [comment]
I wish if it can go beyoned 30

**Comment by ChiSys** [comment]
Fps lock works and seems to help a bit. If blur could be set to 0 and fxaa enabled would help bumping the graphics. Native res only is to much for the vita.

**Comment by ChiSys** [comment]
Not blur DoF I was I want to say.

**Comment by ChiSys** [comment]
Also native res gives me a gpu chrash

**Comment by nad45** [comment]
I am looking forward  to try FPS lock, constantly going between 20 and 40Fps is annoying.
Maybe you could give the values to @Electry for the next Vitagrafix update.

But tooo bad that native resolution doesn't work.
NFSMW, Assassin's Creed and Ratchet Collection are in the same case

**Comment by Electry** [comment]
@nad45 You can try the build I uploaded here: https://github.com/Electry/VitaGrafix/issues/66
It already has the FPS + IB patch for spiderman. You need to add FPS=30 to the config as it isn't the default value though.

960x544 didn't crash for me, but it ran like crap (20fps) and I only tested it for a few minutes.

**Comment by Electry** [comment]
That's unfortunate. Thanks for letting us know.

**Comment by nad45** [comment]
Resolution change makes the game crash but 30fps lock works.
Framedrops are less noticeable  , the game feels smoother.
Thanks @Electry
