### ISSUE TITLE
WRC 5 - Framerate Cap

### ISSUE THREAD

**Issue by ImplyingKinpatsu** [Electry/VitaGrafix#63]
WRC 5 runs at 544p with a 60FPS cap. I could not find any movs.w instructions referencing 544p and changing sceDisplayWaitVblankStartMulti from 1 to 2 did not have any effect on the framerate cap, so I was wondering if you'd know what to do

**Comment by Electry** [comment]
Game uses config file where res. and MaxFPS is stored, which you can easily edit using rePatch. But, changing the MaxFPS var to 30 introduces even more major framepacing issues and tearing. Perhaps something else in the eboot needs to be edited to force it to vsync properly (at 30), I dunno.
