### ISSUE TITLE
[Request] Legend of Heroes: Trails of Cold Steel 2 (PCSB01016 - EU Digital Version) Native Resolution 

### ISSUE THREAD

**Issue by gensosuikoden** [Electry/VitaGrafix#68]
Hi. First of all thank you for sharing these amazing mods. DQ Builders looks amazing at native res compared to the default. Crisp upgrades to Persona 4 and DOA5 too. 

I would like to humbly request a native resolution mod for Legend of Heroes: Trails of Cold Steel 2 (PCSB01016 - EU Digital Version). It is definitely running sub-native at default.

Thank you for your time and once again, your brilliant work thus far. I wasn't going to bother with DQ builders in its default state and was going to get it on Switch or PC instead but am really enjoying it on Vita now.

**Comment by d0kterfreddy** [comment]
I'm Also interested in this. I tried to mess around with the assembler code in the eboot.bin. But I could not make any sense of it.

**Comment by gensosuikoden** [comment]
The patch is in! Tested and works beautifully at native res. Framerate tanks but from my limited testing this this can be remedied with an 'overclock' plugin. Leaving the CPU clock at default seemed fine so unless others experience differently in the course of their own play, I'd suggest leaving the CPU at that to preserve battery and only upclock the GPU.

Thanks Electry and all those who made this happen!
