### ISSUE TITLE
[ISSUE] config.txt problems

### ISSUE THREAD

**Issue by plrusek** [Electry/VitaGrafix#76]
No one reported this yet so I don't know if this is an issue that only I encountered. Anyhow:

I'm able to run this plugin just fine with it's default settings and no config.txt present. However, when booting up, my 3.65 Enso Vita won't go past the logo whenever a config.txt is present in ux0:data/VitaGrafix. It doesn't matter what's written - it breaks even if the .txt file is empty.

Both the VitaGrafix and kuio plugins are in ur0:tai and initiated properly in the tai config.

**Comment by Electry** [comment]
Update to kuio v1.2 from Rinne: https://github.com/Rinnegatamante/kuio/releases

**Comment by TheBLKMN** [comment]
@plrusek Are you using sd2vita? I am, and have the same issue with booting when using the config file or the Configuration Plugin. I also have the latest kuio plugin. Any other time I see this issue pop up, they mention that they are users of sd2vita and can't use a config file with the plugin.

**Comment by Electry** [comment]
I use sd2vita with this just fine

**Comment by plrusek** [comment]
it was the kuio problem for me - the version i had was from old autoplugin which i thought was enough.
