### ISSUE TITLE
[ISSUE] stuck on molecule logo!

### ISSUE THREAD

**Issue by gittyno1** [Electry/VitaGrafix#78]
Whenever i enable vitagrafix in config.txt and reboot vita it gets stuck on molecule logo and i must rebuild database to recover it.

**Comment by denliner** [comment]
I had the same problem, you need to install the latest kuio (you probably got an outdated version from the VSH's Github):
https://github.com/Rinnegatamante/kuio/releases

**Comment by gittyno1** [comment]
Oh! Youre right, i did! Thanks, that solves the issue 😀
