### ISSUE TITLE
Sly Cooper - Not working with Physical

### ISSUE THREAD

**Issue by NikoofDeath** [Electry/VitaGrafix#82]
Apparently, since it includes both Sly 1 and 2, the physical sly collection is PCSA00095 rather than PCSA00096, is it possible to fix this?

**Comment by TheBLKMN** [comment]
@Electry If given this plugin, I could also post the NIDs, as this is a minor issue also plaguing me.

**Comment by Electry** [comment]
Could you please try this? https://github.com/Electry/VitaGrafix/issues/16#issuecomment-419675920

**Comment by TheBLKMN** [comment]
Your test build is almost flawless, dood. Thanks for the awesome work! Keep it up :)
