### ISSUE TITLE
Persona 4 : Dancing All Night

### ISSUE THREAD

**Issue by greggameplayer** [Electry/VitaGrafix#9]
Could you make a resolution patch for Persona 4 : Dancing All Night ?

**Comment by greggameplayer** [comment]
@Electry if you want i can give you the game assembly

**Comment by greggameplayer** [comment]
@Electry yes but if you want to set a higher resolution for ps tv because the ps tv hdmi resolution is 720p

**Comment by shedeus** [comment]
This game already looks awesome on PSTV imo

**Comment by greggameplayer** [comment]
@shedeus awesome is not the word it's look great compared to other games yes but it can look better.
