### ISSUE TITLE
Ninja Gaiden Sigma 2 +

### ISSUE THREAD

**Issue by SheidCraft** [Electry/VitaGrafix#99]
![2018-09-16-185947](https://user-images.githubusercontent.com/42513747/45609068-f67ed700-ba5e-11e8-91c1-7140424764d8.png)
![2018-09-16-185853](https://user-images.githubusercontent.com/42513747/45609069-f7176d80-ba5e-11e8-908b-58c776ef3056.png)
![2018-09-16-190127](https://user-images.githubusercontent.com/42513747/45609070-f8489a80-ba5e-11e8-8a9a-73036795b353.png)
In the test билде 2.5 was added ninja gaiden sigma 2. all looks good and overclocking to 500mhz frame rate пости always stable, but in some moments it can fall to 20fps (this is a very much, given that fps affect the speed of the game). it possible to return to the game dynamic resolution, but not the original 480/416/384, and 544/480/416

**Comment by ChiSys** [comment]
( ͡ಠ ʖ̯ ͡ಠ)
Why a new issue there is an open issue already. Can not understand this behavior. Sorry

But you are right it would be nice to have the option to manipulate/store them separately.

**Comment by Electry** [comment]
It would be possible, but the 3rd. res. would have to either be set to 1:1 aspect ratio (e.g. 416x416) or be the same as 2nd res., because there isn't enough space in the eboot.bin.elf (for 6x MOVS.W).

**Comment by ChiSys** [comment]
Second way should be enough for those minor hickups.

**Comment by Electry** [comment]
Give #102 a try
